### ISSUE TITLE
Example compile error

### ISSUE THREAD

**Issue by vit1251** [iced-rs/iced#1062]
Try to compile clock and receive next on error:

```
error[E0050]: method `update` has 2 parameters but the declaration in trait `iced::Application::update` has 3
  --> src/main.rs:44:15
   |
44 |     fn update(&mut self, message: Message) -> Command<Message> {
   |               ^^^^^^^^^^^^^^^^^^^^^^^^^^^ expected 3 parameters, found 2
   |
   = note: `update` from trait: `fn(&mut Self, <Self as Application>::Message, &mut Clipboard) -> iced::Command<<Self as Application>::Message>`
```

**Comment by hecrj** [comment]
Are you relying on `0.3.0` or `master`?

`master` contains breaking changes. All the examples compile correctly on our CI pipeline.

**Comment by vit1251** [comment]
Documentation version mark is `0.3.0` and as I can see no `Clipboard` in `Counter` example (i.e. second source code block).
My source code is Clock version in my `Cargo.toml` use 0.3 version provide error.

I think that documentation compile on `master` and pushed on `0.3.0` version. Please check.

**Comment by hecrj** [comment]
Which `Counter` example are you specifically referring to? The overview just implements a `Counter` without referencing the `Application` trait.

**Comment by hecrj** [comment]
If you are relying on the `0.3.0` version, please grab the proper example source code from the `0.3.0` tag in the repository:

https://github.com/iced-rs/iced/tree/0.3.0/examples

**Comment by hecrj** [comment]
If the issue you are referring are the outdated links in the docs. The issue has been fixed in `master` by #915.

**Comment by vit1251** [comment]
OK. Thanks.

**Comment by vit1251** [comment]
Dut documenataion for 0.3.0 contain modern contract in https://github.com/iced-rs/iced/blob/0.3/src/lib.rs#L147
