### ISSUE TITLE
New release required to work with iced_aw 0.8.0?

### ISSUE THREAD

**Issue by andrewdavidmackenzie** [iced-rs/iced#2296]
### Is there an existing issue for this?

- [X] I have searched the existing issues.

### Is this issue related to iced?

- [X] My hardware is compatible and my graphics drivers are up-to-date.

### What happened?

I am trying to update to latest versions of iced and iced_aw.
I am currently trying
- iced v0.12.1 
- iced_aw v0.8.0

On building I get this new error (no code changes on my side):
```
iced_native v0.10.3
   Compiling iced v0.12.1
   Compiling iced_aw v0.8.0
   Compiling multimap v0.10.0
   Compiling flowc v0.142.0 (/Users/andrew/workspace/flow/flowc)
   Compiling zmq v0.10.0
   Compiling flowr v0.142.0 (/Users/andrew/workspace/flow/flowr)
error[E0275]: overflow evaluating the requirement `&_: IntoIterator`
  |
  = help: consider increasing the recursion limit by adding a `#![recursion_limit = "256"]` attribute to your crate (`flowrgui`)
  = note: required for `&objc2::rc::id::Id<_>` to implement `IntoIterator`
  = note: 126 redundant requirements hidden
  = note: required for `&Id<Id<Id<Id<Id<Id<Id<Id<Id<Id<Id<Id<Id<Id<Id<Id<Id<Id<Id<Id<...>>>>>>>>>>>>>>>>>>>>` to implement `IntoIterator`
  = note: the full type name has been written to '/Users/andrew/workspace/flow/target/debug/deps/flowrgui-48eecd641750c493.long-type-16348972021002123372.txt'

error[E0275]: overflow evaluating the requirement `&_: IntoIterator`
  |
  = help: consider increasing the recursion limit by adding a `#![recursion_limit = "256"]` attribute to your crate (`flowrgui`)
  = note: required for `&objc2::rc::id::Id<_>` to implement `IntoIterator`
  = note: 126 redundant requirements hidden
  = note: required for `&Id<Id<Id<Id<Id<Id<Id<Id<Id<Id<Id<Id<Id<Id<Id<Id<Id<Id<Id<Id<...>>>>>>>>>>>>>>>>>>>>` to implement `IntoIterator`
  = note: the full type name has been written to '/Users/andrew/workspace/flow/target/debug/deps/flowrgui-48eecd641750c493.long-type-4448879348208403115.txt'

For more information about this error, try `rustc --explain E0275`.
error: could not compile `flowr` (bin "flowrgui") due to 2 previous errors
warning: build failed, waiting for other jobs to finish...
make: *** [build] Error 101
andrew@MacBook-Pro flow % more /Users/andrew/workspace/flow/target/debug/deps/flowrgui-48eecd641750c493.long-type-16348972021002123372.txt
&objc2::rc::id::Id<objc2::rc::id::Id<objc2::rc::id::Id<objc2::rc::id::Id<objc2::rc::id::Id<objc2::rc::id::Id<objc2::rc::id::Id<objc2::rc::id::Id<objc2::rc::id::Id<objc2::rc::id::Id<objc2::rc::id::Id<objc2::rc::id::Id<objc2::rc::id::Id<objc2::rc::id::Id<objc2::rc::id::Id<objc2::rc::i.......<truncated by me>
```

### What is the expected behavior?

I expected the latest versions of these two crates to play together as-is, but maybe a new release of iced is required?
Either way, any suggestions on how to fix it are welcome

### Version

crates.io release

### Operating System

macOS

### Do you have any log output?

```shell
Compiling iced_core v0.9.0
   Compiling cranelift-wasm v0.105.1
   Compiling iced_winit v0.12.2
   Compiling wasmtime-cranelift v18.0.1
   Compiling iced_style v0.8.0
   Compiling flowmacro v0.142.0 (/Users/andrew/workspace/flow/flowmacro)
   Compiling wgpu v0.19.1
   Compiling glyphon v0.5.0
   Compiling iced_wgpu v0.12.1
   Compiling wasmtime v18.0.1
   Compiling iced_renderer v0.12.1
   Compiling iced_widget v0.12.1
   Compiling flowstdlib v0.142.0 (/Users/andrew/workspace/flow/flowstdlib)
   Compiling iced_native v0.10.3
   Compiling iced v0.12.1
   Compiling iced_aw v0.8.0
   Compiling multimap v0.10.0
   Compiling flowc v0.142.0 (/Users/andrew/workspace/flow/flowc)
   Compiling zmq v0.10.0
   Compiling flowr v0.142.0 (/Users/andrew/workspace/flow/flowr)
error[E0275]: overflow evaluating the requirement `&_: IntoIterator`
  |
  = help: consider increasing the recursion limit by adding a `#![recursion_limit = "256"]` attribute to your crate (`flowrgui`)
  = note: required for `&objc2::rc::id::Id<_>` to implement `IntoIterator`
  = note: 126 redundant requirements hidden
  = note: required for `&Id<Id<Id<Id<Id<Id<Id<Id<Id<Id<Id<Id<Id<Id<Id<Id<Id<Id<Id<Id<...>>>>>>>>>>>>>>>>>>>>` to implement `IntoIterator`
  = note: the full type name has been written to '/Users/andrew/workspace/flow/target/debug/deps/flowrgui-48eecd641750c493.long-type-16348972021002123372.txt'

error[E0275]: overflow evaluating the requirement `&_: IntoIterator`
  |
  = help: consider increasing the recursion limit by adding a `#![recursion_limit = "256"]` attribute to your crate (`flowrgui`)
  = note: required for `&objc2::rc::id::Id<_>` to implement `IntoIterator`
  = note: 126 redundant requirements hidden
  = note: required for `&Id<Id<Id<Id<Id<Id<Id<Id<Id<Id<Id<Id<Id<Id<Id<Id<Id<Id<Id<Id<...>>>>>>>>>>>>>>>>>>>>` to implement `IntoIterator`
  = note: the full type name has been written to '/Users/andrew/workspace/flow/target/debug/deps/flowrgui-48eecd641750c493.long-type-4448879348208403115.txt'

For more information about this error, try `rustc --explain E0275`.
error: could not compile `flowr` (bin "flowrgui") due to 2 previous errors
warning: build failed, waiting for other jobs to finish...
make: *** [build] Error 101
andrew@MacBook-Pro flow % more /Users/andrew/workspace/flow/target/debug/deps/flowrgui-48eecd641750c493.long-type-16348972021002123372.txt
&objc2::rc::id::Id<objc2::rc::id::Id<objc2::rc::id::Id<objc2::rc::id::Id<objc2::rc::id::Id<objc2::rc::id::Id<objc2::rc::id::Id<objc2::rc::id::Id<objc2::rc::id::Id<objc2::rc::id::Id<objc2::rc::id::Id<objc2::rc::id::Id<objc2::rc::id::Id<objc2::rc::id::Id<objc2::rc::id::Id<objc2::rc::id::Id<objc2::rc::id::Id<objc2::rc::id::Id<objc2::rc::id::Id<objc2::rc::id::Id<objc2::rc::id::Id<objc2::rc::id::Id<objc2::rc::id::Id<objc2::rc::id::Id<objc2::rc::id::Id<objc2::rc::id::Id<objc2::rc::id::Id<objc2::rc::id::Id<objc2::rc::id::Id<objc2::rc::id::Id<objc2::rc::id::Id<objc2::rc::id::Id<objc2::rc::id::Id<objc2::rc::id::Id<objc2::rc::id::Id<objc2::rc::id::Id<objc2::rc::id::Id<objc2::rc::id::Id<objc2::rc::id::Id<objc2::rc::id::Id<objc2::rc::id::Id<objc2::rc::id::Id<objc2::rc::id::Id<objc2::rc::id::Id<objc2::rc::id::Id<objc2::rc::id::Id<objc2::rc::id::Id<objc2::rc::id::Id<objc2::rc::id::Id<objc2::rc::id::Id<objc2::rc::id::Id<objc2::rc::id::Id<objc2::rc::id::Id<objc2::rc::id::Id<objc2::rc::id::Id<objc2::rc::id::Id<objc2::rc::id::Id<objc2::rc::id::Id<objc2::rc::id::Id<objc2::rc::id::Id<objc2::rc::id::Id<objc2::rc::id::Id<objc2::rc::id::Id<objc2::rc::id::Id<objc2::rc::id::Id<objc2::rc::id::Id<objc2::rc::id::Id<objc2::rc::id::Id<objc2::rc::id::Id<objc2::rc::id::Id<objc2::rc::id::Id<objc2::rc::id::Id<objc2::rc::id::Id<objc2::rc::id::Id<objc2::rc::id::Id<objc2::rc::id::Id<objc2::rc::id::Id<objc2::rc::id::Id<objc2::rc::id::Id<objc2::rc::id::Id<objc2::rc::id::Id<objc2::rc::id::Id<objc2::rc::id::Id<objc2::rc::id::Id<objc2::rc::id::Id<objc2::rc::id::Id<objc2::rc::id::Id<objc2::rc::id::Id<objc2::rc::id::Id<objc2::rc::id::Id<objc2::rc::id::Id<objc2::rc::id::Id<objc2::rc::id::Id<objc2::rc::id::Id<objc2::rc::id::Id<objc2::rc::id::Id<objc2::rc::id::Id<objc2::rc::id::Id<objc2::rc::id::Id<objc2::rc::id::Id<objc2::rc::id::Id<objc2::rc::id::Id<objc2::rc::id::Id<objc2::rc::id::Id<objc2::rc::id::Id<objc2::rc::id::Id<objc2::rc::id::Id<objc2::rc::id::Id<objc2::rc::id::Id<objc2::rc::id::Id<objc2::rc::id::Id<objc2::rc::id::Id<objc2::rc::id::Id<objc2::rc::id::Id<objc2::rc::id::Id<objc2::rc::id::Id<objc2::rc::id::Id<objc2::rc::id::Id<objc2::rc::id::Id<objc2::rc::id::Id<objc2::rc::id::Id<objc2::rc::id::Id<objc2::rc::id::Id<objc2::rc::id::Id<objc2::rc::id::Id<objc2::rc::id::Id<objc2::rc::id::Id<_>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>
```

**Comment by genusistimelord** [comment]
can you show us a minimal example of the code breaking? as this seems like its a macro issue.

**Comment by andrewdavidmackenzie** [comment]
I'll try, but it doesn't report the source line or file where it's happening - so it may take me a while.
It's going to be somewhere in here: https://github.com/andrewdavidmackenzie/flow/tree/master/flowr/src/bin/flowrgui

**Comment by andrewdavidmackenzie** [comment]
Excellent. That solved the issue. Thank You.
